// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-PKxD9gHvF6LxyfWfJciszD6lBOcm0cM',
    appId: '1:356016332536:web:dbf376169278461d18650d',
    messagingSenderId: '356016332536',
    projectId: 'clockapp-4948d',
    authDomain: 'clockapp-4948d.firebaseapp.com',
    storageBucket: 'clockapp-4948d.firebasestorage.app',
    measurementId: 'G-CGWSYM99Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApTgxi1XQ_eGdVdChxRwD1beQ3oen3C6A',
    appId: '1:356016332536:android:c2cf7ab93f4860e618650d',
    messagingSenderId: '356016332536',
    projectId: 'clockapp-4948d',
    storageBucket: 'clockapp-4948d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRPxGLddCHXkVRfTrGeJs5rlLLHLsN0XQ',
    appId: '1:356016332536:ios:120762cdcb8c8c7e18650d',
    messagingSenderId: '356016332536',
    projectId: 'clockapp-4948d',
    storageBucket: 'clockapp-4948d.firebasestorage.app',
    iosBundleId: 'com.example.clockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRPxGLddCHXkVRfTrGeJs5rlLLHLsN0XQ',
    appId: '1:356016332536:ios:120762cdcb8c8c7e18650d',
    messagingSenderId: '356016332536',
    projectId: 'clockapp-4948d',
    storageBucket: 'clockapp-4948d.firebasestorage.app',
    iosBundleId: 'com.example.clockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-PKxD9gHvF6LxyfWfJciszD6lBOcm0cM',
    appId: '1:356016332536:web:87f78c50120656fe18650d',
    messagingSenderId: '356016332536',
    projectId: 'clockapp-4948d',
    authDomain: 'clockapp-4948d.firebaseapp.com',
    storageBucket: 'clockapp-4948d.firebasestorage.app',
    measurementId: 'G-52QVXM66L6',
  );
}
